import { Country } from '../models/country';

export const COUNTRIES: Country[] = [
  {
    id: 1,
    name: 'United States',
    currency: 'USD',
    currencyCode: 'USD',
    exchangeRate: 1,
    cashPickup: true,
    bankAccount: true,
  },
  {
    id: 2,
    name: 'India',
    currency: 'Indian Rupee',
    currencyCode: 'INR',
    exchangeRate: 66.8866,
    cashPickup: true,
    bankAccount: true,
  },
  {
    id: 3,
    name: 'Philippines',
    currency: 'Philippine Peso',
    currencyCode: 'PHP',
    exchangeRate: 51.5348,
    cashPickup: true,
    bankAccount: true,
  },
  {
    id: 4,
    name: 'China',
    currency: 'Chinese Yuan Renminbi',
    currencyCode: 'CNY',
    exchangeRate: 6.3470,
    cashPickup: true,
    bankAccount: true,
  },
  {
    id: 5,
    name: 'Mexico',
    currency: 'Mexican Peso',
    currencyCode: 'MXN',
    exchangeRate: 19.7539,
    cashPickup: true,
    bankAccount: true,
  },
  {
    id: 6,
    name: 'Jamaica',
    currency: 'Jamaican Dollar',
    currencyCode: 'JMD',
    exchangeRate: 123.2811,
    cashPickup: true,
    bankAccount: false,
  },
  {
    id: 7,
    name: 'Colombia',
    currency: 'Colombian Peso',
    currencyCode: 'COP',
    exchangeRate: 2747.5200,
    cashPickup: true,
    bankAccount: false,
  },
];
