import { Country } from '../models/country';

export const COUNTRIES: Country[] = [
  {
    id: 1,
    name: 'United States',
    code: 'US',
    currency: 'USD',
    currencyCode: 'USD',
    exchangeRate: 1,
    cashPickup: true,
    bankAccount: true,
    cashPickupCreditCardTransferFee: 25.99,
    cashPickupBankAccountTransferFee: 11.00,
    cashPickupPayInStoreTransferFee: 5.00,
    bankAccountCreditCardTransferFee: 12.00,
    bankAccountBankAccountTransferFee: 0.99,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 2,
    name: 'India',
    code: 'IN',
    currency: 'Indian Rupee',
    currencyCode: 'INR',
    exchangeRate: 66.8866,
    cashPickup: true,
    bankAccount: true,
    cashPickupCreditCardTransferFee: 10.00,
    cashPickupBankAccountTransferFee: 6.00,
    cashPickupPayInStoreTransferFee: 8.00,
    bankAccountCreditCardTransferFee: 2.99,
    bankAccountBankAccountTransferFee: 0.00,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 3,
    name: 'Philippines',
    code: 'PH',
    currency: 'Philippine Peso',
    currencyCode: 'PHP',
    exchangeRate: 51.5348,
    cashPickup: true,
    bankAccount: true,
    cashPickupCreditCardTransferFee: 7.00,
    cashPickupBankAccountTransferFee: 3.99,
    cashPickupPayInStoreTransferFee: 5.00,
    bankAccountCreditCardTransferFee: 5.00,
    bankAccountBankAccountTransferFee: 0.00,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 4,
    name: 'China',
    code: 'CN',
    currency: 'Chinese Yuan Renminbi',
    currencyCode: 'CNY',
    exchangeRate: 6.3470,
    cashPickup: true,
    bankAccount: true,
    cashPickupCreditCardTransferFee: 75.00,
    cashPickupBankAccountTransferFee: 26.00,
    cashPickupPayInStoreTransferFee: 10.00,
    bankAccountCreditCardTransferFee: 0.00,
    bankAccountBankAccountTransferFee: 0.00,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 5,
    name: 'Mexico',
    code: 'MX',
    currency: 'Mexican Peso',
    currencyCode: 'MXN',
    exchangeRate: 19.7539,
    cashPickup: true,
    bankAccount: true,
    cashPickupCreditCardTransferFee: 9.00,
    cashPickupBankAccountTransferFee: 5.00,
    cashPickupPayInStoreTransferFee: 6.00,
    bankAccountCreditCardTransferFee: 2.99,
    bankAccountBankAccountTransferFee: 2.99,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 6,
    name: 'Jamaica',
    code: 'JM',
    currency: 'Jamaican Dollar',
    currencyCode: 'JMD',
    exchangeRate: 123.2811,
    cashPickup: true,
    bankAccount: false,
    cashPickupCreditCardTransferFee: 15.99,
    cashPickupBankAccountTransferFee: 7.99,
    cashPickupPayInStoreTransferFee: 5.00,
    bankAccountCreditCardTransferFee: 0.00,
    bankAccountBankAccountTransferFee: 0.00,
    bankAccountPayInStoreTransferFee: 0.00,
  },
  {
    id: 7,
    name: 'Colombia',
    code: 'CO',
    currency: 'Colombian Peso',
    currencyCode: 'COP',
    exchangeRate: 2747.5200,
    cashPickup: true,
    bankAccount: false,
    cashPickupCreditCardTransferFee: 16.00,
    cashPickupBankAccountTransferFee: 9.00,
    cashPickupPayInStoreTransferFee: 6.00,
    bankAccountCreditCardTransferFee: 0.00,
    bankAccountBankAccountTransferFee: 0.00,
    bankAccountPayInStoreTransferFee: 0.00,
  },
];
